name:                traversabless
version:             0.1.0.0
github:              "githubuser/traversabless"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/traversabless#readme>

dependencies:
- base >= 4.7 && < 5
- wreq == 0.5.3.2
- bytestring
- lens == 4.17.1
- transformers == 0.5.6.2

library:
  source-dirs: src

executables:
  traversabless-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - traversabless

tests:
  traversabless-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - traversabless
    - QuickCheck
    - checkers
